apiVersion: v1
kind: Service
metadata:
  # annotations:
  #  service.beta.kubernetes.io/oci-load-balancer-shape: 400Mbps
  name: kibana
  namespace: "{{ .Values.efk.namespace }}"
  labels:
    # k8s-app: {{ .Release.Name }}-kibana-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    # kubernetes.io/name: "Kibana"
    app: kibana
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    # k8s-app: {{ .Release.Name }}-kibana-logging
    app: kibana
  # type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: "{{ .Values.efk.namespace }}"
  labels:
    # k8s-app: {{ .Release.Name }}-kibana-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      # k8s-app: {{ .Release.Name }}-kibana-logging
      app: kibana
  template:
    metadata:
      labels:
        # k8s-app: {{ .Release.Name }}-kibana-logging
        app: kibana
      # annotations:
      #  seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:{{ .Values.kibana.version }}
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
